# Generated by Django 2.1.7 on 2019-06-12 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0002_auto_20190612_0713'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likerecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='favoriterecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyboxingredient',
            name='daily_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.DailyBox'),
        ),
        migrations.AddField(
            model_name='dailyboxingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredients'),
        ),
        migrations.AddField(
            model_name='dailybox',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likerecipe',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='favoriterecipe',
            unique_together={('user', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyboxingredient',
            unique_together={('daily_box', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='dailybox',
            unique_together={('user', 'day_of_week')},
        ),
    ]
