# Generated by Django 2.1.7 on 2019-06-12 07:13

import json

from django.conf import settings
from django.db import migrations

from apps.food.utils import get_ingredient_source_types


def insert_ingredients_data(apps, schema_editor):
    Ingredients = apps.get_model('food', 'Ingredients')

    with open(settings.BASE_DIR + '/fixtures/ingredients.json') as f:
        data = json.load(f)
    for x in data:
        if not Ingredients.objects.filter(name=x['name']).exists():
            types = get_ingredient_source_types(x)
            ingredient = Ingredients(
                name=x['name'],
                protein=x['protein'],
                fat=x['fat'],
                carbohydrate=x['carbohydrate'],
                fiber=x['fiber'],
                energy=x['energy'],
                sugar=x['sugar'],
                source_type=types['source_type'],
                sub_source_type=types['sub_source_type'],
                status=1,
            )
            ingredient.save()


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_auto_20190612_0713'),
    ]

    operations = [
        migrations.RunPython(
            code=insert_ingredients_data,
            reverse_code=migrations.RunPython.noop
        ),
    ]
