# Generated by Django 2.1.7 on 2019-06-17 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20190612_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='daily_box',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.DailyBox'),
            preserve_default=False,
        ),
    ]
